Repository ucsb-cs156-s24/proj-organic-s24-5pm-1, pull requests merged in 2024-05, with the labels that each got.

#8 PM - working on the info for the home page
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/pages/HomePage.test.js
Labels: 10

#18 Create Student Table (but no interface to view it yet)
  frontend/src/fixtures/studentFixture.js
  frontend/src/main/components/Student/StudentTable.js
  frontend/src/stories/components/Student/StudentTable.stories.js
  frontend/src/tests/components/Student/StudentTable.test.js
Labels: 10

#17 rt.z - Expose commit info on api/systemInfo
  Dockerfile
  pom.xml
  src/main/java/edu/ucsb/cs156/organic/intercepters/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/intercepters/RoleUserInterceptorAppConfig.java
  src/main/java/edu/ucsb/cs156/organic/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/organic/services/SystemInfoServiceImpl.java
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptorTests.java
  src/test/java/edu/ucsb/cs156/organic/services/SystemInfoServiceImplTests.java
Labels: FixMe - Peer CR needed

#29 update imports and functions in backend to spring 3
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  pom.xml
  src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/entities/Course.java
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/entities/Staff.java
  src/main/java/edu/ucsb/cs156/organic/entities/Student.java
  src/main/java/edu/ucsb/cs156/organic/entities/User.java
  src/main/java/edu/ucsb/cs156/organic/entities/UserEmail.java
  src/main/java/edu/ucsb/cs156/organic/entities/jobs/Job.java
  src/main/java/edu/ucsb/cs156/organic/intercepters/RoleUserInterceptor.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/TestConfig.java
Labels: 10

#31 fix the local host for spring 3
  src/main/java/edu/ucsb/cs156/organic/controllers/FrontendProxyController.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/TestConfig.java
Labels: 0
